apiVersion: datarefinery.cpd.ibm.com/v1beta1
kind: DataRefinery
metadata:
 name: datarefinery-cr
spec:
 version: "4.0.0"
 size: "small"
 is_35_upgrade: false
 storageClass: "portworx-shared-gp3"
 license:
  accept: true
  license: Enterprise
 docker_registry_prefix: cp.icr.io/cp/cpd