apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-dmc-operator-subscription 
  namespace: CPD_OPERATORS_NAMESPACE    # Pick the project that contains the Cloud Pak for Data operator
spec:
  channel: v1.0
  installPlanApproval: Automatic
  name: ibm-dmc-operator
  source: ibm-dmc-operator-catalog
  sourceNamespace: openshift-marketplace